# Generated by Django 5.2 on 2025-04-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
    ]
