# Generated by Django 5.1.7 on 2025-04-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
    ]
